FROM centos

RUN yum install -y java

VOLUME /tmp
ADD /spring-boot-web-0.0.1-SNAPSHOT.jar myapp.jar
#update timestamp
RUN sh -c 'touch /myapp.jar'
# https://gandharvkapoor.wordpress.com/2017/02/23/spring-boot-slow-boot-up-random-vs-urandom/
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar","/myapp.jar"]